const Constants = {
  TIMING: {
    GROUP_DELAY_MS: 300,
    RETRY_DELAY_MS: 200,
    RETRY_MAX_ATTEMPTS: 3,
    RETRY_BASE_DELAY_MS: 100,
  },
  LIMITS: {
    MAX_TABS_PER_GROUP: 100,
    MAX_GROUPS: 50,
    MAX_DOMAINS_PER_GROUP: 100,
    STORAGE_QUOTA_BYTES: 102400,
    STORAGE_QUOTA_ITEM_BYTES: 8192,
  }
};
